apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP # Service Type: gives Service obj internal IP accessible within cluster
  selector:
    app: ping-pong-be
    version: "2.03"
    component: backend
  ports:
    - name: http
      port: 2366 # Service port -- can be anything
      targetPort: http-ping-pong # target port access for other pods in cluster
      protocol: TCP
