apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  labels:
    app: ping-pong-be
    version: "2.03"
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-be
      version: "2.03"
      component: backend
  template:
    metadata:
      labels:
        app: ping-pong-be
        version: "2.03"
        component: backend
    spec:
      containers:
        - name: ping-pong-be-ctr
          image: michaelangelovalente/ping_pong_img:ex2.03
          env:
            - name: PORT
              value: "8096"
          ports:
            - name: http-ping-pong
              containerPort: 8096
              protocol: TCP
