apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-app-claim
spec:
  storageClassName: todo-app-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
