apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
  labels:
    app: todo-app
    version: "2.06"
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      version: "2.06"
      component: frontend
  template:
    metadata:
      namespace: project
      labels:
        app: todo-app
        version: "2.06"
        component: frontend
    spec:
      securityContext:
        fsGroup: 1001
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app-ctr
          image: michaelangelovalente/todo_app_fe_img:ex2.06
          # Kubernetes level port declaration
          ports:
            - name: http-todo-app
              containerPort: 3066
              protocol: TCP
          envFrom:
            - configMapRef:
                name: todo-app-fe-cfgm
          # Volume Mount - Mounts PVC-backed volume
          volumeMounts:
            - name: image-storage
              mountPath: /app/tmp/images #Path in container

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
