apiVersion: v1
kind: Service
metadata:
  name: pingpong-psql-db-svc
  labels:
    app: pingpong-psql-db
    version: "2.07"
spec:
  ports:
    - port: 5432
      name: http-psql-db
  clusterIP: None
  selector:
    app: pingpong-psql-db
    version: "2.07"
    component: database
