apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-be-svc
spec:
  type: ClusterIP # Service Type: gives Service obj internal IP accessible within cluster
  selector:
    app: todo-be
    version: "2.04"
    component: backend
  ports:
    - name: http
      # Service port -- can be anything
      port: 2386
      targetPort: http-todo-be # app port -- reader port --> using named port as target.  target port access for other pods in cluster
      protocol: TCP
