apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
    version: "2.04"
    component: frontend
  ports:
    - name: http
      port: 2006
      targetPort: http-todo-app
      protocol: TCP
