apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
  labels:
    app: ping-pong-be
    version: "2.07"
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-be
      version: "2.07"
      component: backend
  template:
    metadata:
      namespace: exercises
      labels:
        app: ping-pong-be
        version: "2.07"
        component: backend
    spec:
      containers:
        - name: ping-pong-be-ctr
          image: michaelangelovalente/ping_pong_img:ex2.07
          env:
            - name: PORT
              value: "8096"
            - name: DB_HOST
              value: "pingpong-psql-db-svc" # StatefulSet headless service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "pingpong"
            - name: DB_SCHEMA
              value: "public"

          ports:
            - name: http-ping-pong
              containerPort: 8096
              protocol: TCP
