apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  labels:
    app: todo-app
    version: "2.02"
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      version: "2.02"
      component: fe-be
  template:
    metadata:
      labels:
        app: todo-app
        version: "2.02"
        component: fe-be
    spec:
      containers:
        - name: todo-app-ctr
          image: michaelangelovalente/log_output-img:ex2.01
          env:
            # Application level env var (consumed by actual app)
            # - name: LOG_OUTPUT_PORT
            - name: PORT
              value: "8095"
            - name: PING_PONG_SVC_URL
              value: http://pingpong-svc:2366
          # Kubernetes level port declaration
          ports:
            - name: http-logoutput
              containerPort: 8095
              protocol: TCP
        - name: pingpong-ctr
          image: michaelangelovalente/ping_pong_img:ex2.01
          env:
            # Application level env var (consumed by actual app)
            - name: PORT
              value: "8096"
          # Kubernetes level port declaration
          ports:
            - name: http-pingpong
              containerPort: 8096
              protocol: TCP
